### ISSUE TITLE
License ambiguity again

### ISSUE THREAD

**Issue by pghmcfc** [briandfoy/module-extract-namespaces#4]
This old chestnut again.

The 'LICENSE' file says that the module is licensed "under the same terms as perl itself, under the Artistic License 2.0", which is self-contradicting because perl is licensed under either GPL or Artistic 1 licenses, not Artistic 2. The text in the module file itself says "Artistic 2.0", so it would probably be better to get rid of the "same as perl" text everywhere and just say "Artistic 2.0" instead.

**Comment by briandfoy** [comment]
Fixed, thanks,
